networks:
  caddy:
services:
  frontend:
    build: frontend
    ports:
     - 3000:3000
    networks:
      - caddy
    env_file:
      - "frontend/.env"
  
  backend:
    build: backend
    ports:
     - 4000:4000
    networks:
     - caddy
    depends_on:
      - mongo
    env_file:
      - "backend/.env"
    environment:
      - DB_URI=mongodb://mongo:27017/lambda
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - caddy
    volumes:
      - /home/opc/mongo-data:/data/db
  
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/opc/containers/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/opc/containers/caddy/site:/srv
      - /home/opc/containers/caddy/caddy_data:/data
      - /home/opc/containers/caddy/caddy_config:/config
    networks:
      - caddy


volumes:
  mongo-data:
    external: true
  caddy_data:
    external: true
  caddy_config:
  